class GeneralError(Exception): ...


class VideoNotFoundError(GeneralError): ...


class InferenceNotFoundError(GeneralError): ...


class InferencesNotFoundError(GeneralError): ...


class EmptyRepositoryError(GeneralError): ...
